name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - name: Test 2021
      run: cd 2021 && sbt test
    - name: Test 2022
      run: cd 2022 && sbt test
    - name: Test 2023
      run: cd 2023 && sbt test
