name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        year: [2021, 2022, 2023]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Decrypt inputs
      uses: sliteteam/github-action-git-crypt-unlock@1.2.0
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
    - uses: coursier/cache-action@v6
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - name: Test
      run: cd ${{matrix.year}} && sbt test
